# Generated by Django 2.1.3 on 2018-12-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0003_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='Query',
            field=models.CharField(default=5, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='email',
            field=models.EmailField(default=5, max_length=254),
            preserve_default=False,
        ),
    ]
